# Copyright 2019-2021 Canonical Ltd.
#
# This file is part of the SYSConfig Charm for Juju.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranties of
# MERCHANTABILITY, SATISFACTORY QUALITY, or FITNESS FOR A PARTICULAR
# PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
options:
  enable-container:
    type: boolean
    default: false
    description: |
        Enable support for containers.
        For testing purpose only.
  reservation:
    type: string
    default: "off"
    description: |
        Type of CPU reservation: isolcpus, affinity, off
        isolcpus is a kernel cmdline parameter
        affinity (CPU Affinity) is a systemd configuration parameter.
        Other processes inherit from systemd-system.conf
        off (default) disables any CPU reservation on host-side.

        [DEPRECATED]: this option should no longer be used.
        Instead isolcpus and cpu-affinity-range should be used.
  cpu-affinity-range:
    type: string
    default: ""
    description: |
        Single pcpus (0,1,2) or range of pcpus (0-10)

        This will update /etc/systemd/system.conf and update the CPUAffinity
        variable with the option here
  cpu-range:
    type: string
    default: ""
    description: |
        Single pcpus (0,1,2) or range of pcpus (0-10) to isolate (if
        isolcpus is selected) or reserve (if affinity is selected).
        Default value (empty) will make "reservation" work as if it was
        "off".

        [DEPRECATED]: this option should no longer be used.
        Instead isolcpus and cpu-affinity-range should be used.
  hugepages:
    type: string
    default: ""
    description: |
        Number of hugepages. Example: 400
  hugepagesz:
    type: string
    default: ""
    description: |
        Size of each hugepage. Example: 1G
  default-hugepagesz:
    type: string
    default: ""
    description: |
        Size of default hugepage. Example: 1G
  raid-autodetection:
    type: string
    default: ""
    description: |
        Configure raid detection. Possible value are
        - '': (default) autodetection enabled if md module is compiled into the kernel
        - 'noautodetect': autodetection is disabled
        - 'partitionable': all auto-detected arrays are assembled as partitionable
  enable-pti:
    type: string
    default: ""
    description: |
        Allow enabling/disabling page table isolation, adding pti=on/off to grub cmdline
        Allowed values are 'on' or 'off'. Default is unset, to have the upstream
        configuration as the default.
  enable-iommu:
    type: boolean
    default: false
    description: |
        If true and VT-d enabled in the BIOS, it will allow to use direct I/O
        bypassing DMA translation with pci-passthrough devices.
        Enable it to use SR-IOV
  enable-tsx:
    type: boolean
    default: false
    description: |
        If true then tsx=on tsx_async_abort=off is passed on the grub command line. On
        all new kernel this is disabled by default, and this option will re-enable it.

        More information on the details can be found in the following URL:
          https://wiki.ubuntu.com/SecurityTeam/KnowledgeBase/TAA_MCEPSC_i915
  config-flags:
    default: ""
    type: string
    description: |
      If extra lines need to be configured on /etc/default/grub
      (isolcpus) or /etc/systemd/system.conf (affinity), this string
      can be used as a list in yaml format.
      Sample:
        {'grub': 'key1=value1, key2=value2', 'systemd': 'key1=value1'}

      [DEPRECATED]: this option should no longer be used.
      Instead grub-config-flags and systemd-config-flags should be used.
  grub-config-flags:
    default: ""
    type: string
    description: |
        If extra lines need to be configured on /etc/default/grub
        this string can be used as a list of key/value pairs
        'key1=value1,key2=value2'.  If you want to add additional parameters to
        GRUB_CMDLINE_LINUX_DEFAULT, then you need to include the existing items
        to avoid them being overwritten, for example
        grub-config-flags='GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT
        nvme_core.multipath=0'
        Also supports adding values with special characters in them(`$`, `=`, `,` etc.)
        but they need to be enclosed in double quotes. For example, grub-config-flags='GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT
        console=ttyS0,115200 console=tty0",GRUB_TIMEOUT=0'
  isolcpus:
    default: ""
    type: string
    description:
        Single pcpus (0,1,2) or range of pcpus (0-10)

        isolcpus is a kernel cmdline parameter, and will append isolcpus to the
        grub command line with the option given here.
  kernel-version:
    type: string
    default: ""
    description: |
        Upgrade kernel and modules-extra package to this version and add GRUB_DEFAULT to
        /etc/default/grub to load the required kernel version. Does
        nothing if same kernel already running.
  update-grub:
    type: boolean
    default: false
    description: |
        Allows the charm to run "update-grub" command if
        /etc/default/grub was changed.
        This is discouraged and by default it is disabled.
  systemd-config-flags:
    default: ""
    type: string
    description: |
        If extra lines need to be configured on /etc/systemd/system.conf
        this string can be used as a list of key/value pairs
        'key1=value1,key2=value2'
  governor:
    type: string
    default: ""
    description: |
        Configured via cpufrequtils, possible values are:
        - '' (default): systemd will choose the first available between
                        'ondemand', 'powersave', 'performance'.
                        Recommended option when Bios control power is set to the OS.
        - 'performance'
        - 'powersave'

        On some architectures, cpufrequtils is not available.
        In these cases, this config option will be ignored.
  resolved-cache-mode:
    type: string
    default: ""
    description: |
        Sets the "Cache" configuration value in /etc/systemd/resolved.conf.  Valid
        values are '' (system default), 'yes', 'no', and 'no-negative'.
  sysctl:
    type: string
    default: ""
    description: |
      YAML-formatted associative array of sysctl key/value pairs to be set
      persistently.

      eg. { kernel.max_pid: 1337, net.ipv4.ip_forward: 0 }
  irqbalance-banned-cpus:
    type: string
    default: ""
    description: |
      64 bit bitmask which allows you to indicate which CPU's should
      be skipped when reblancing irqs.  CPU numbers which have their
      corresponding bits set to one in this mask will not have any
      IRQs assigned to them on rebalance
