name: Check workflow running linter, unit and functional tests

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master, main]
    paths-ignore:
      - "**.md"
      - "**.rst"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint-unit:
    uses: canonical/bootstack-actions/.github/workflows/lint-unit.yaml@v2
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.10"]
    with:
      python-version: ${{ matrix.python-version }}
      working-directory: "./src"
  func:
    needs: lint-unit
    name: functional tests
    runs-on: ${{ matrix.architecture.runs-on }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        juju-channel: ["3.4/stable"]
        architecture:
          - runs-on: [self-hosted, jammy, X64, large]
            mondel-constraints: ""
          # Functional test failed due to the support of LXD VM on ARM64
          # - runs-on: [self-hosted, jammy, ARM64, medium]
          #   model-constraints: arch=arm64
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Setup juju environement
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: "lxd"
          juju-channel: ${{ matrix.juju-channel }}
          charmcraft-channel: "2.x/stable"
      - name: Show juju information
        run: |
          juju version
          juju controllers | grep version -A 1 | awk '{print $9}'
      - name: Install latest tox version
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Run tests
        run: "make functional"
        env:
          TEST_MODEL_CONSTRAINTS: ${{ matrix.architecture.model-constraints }}
